language: r

cache: packages

warnings_are_errors: true

r_github_packages:
  - jimhester/covr
  - jakobbossek/re

# Fix problem with error/warning: no DISPLAY variable so Tk is not available
# Source: https://github.com/travis-ci/travis-ci/issues/6987
before_install:
  - sudo apt-get install r-cran-tcltk2

after_success:
  - Rscript -e 'library(covr);coveralls()'

notifications:
  email:
    recipients:
      - bossek@wi.uni-muenster.de
    on_success: change
    on_failure: always
